- id: 10.1007/978-3-031-43699-4_42
  type: paper
  description: Humans As Sensors in Urban Digital Twins
  image: https://www.researchgate.net/profile/Filip-Biljecki/publication/378355824/figure/fig1/AS:11431281225580244@1708845623746/The-framework-of-human-centric-urban-digital-twins.png
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - digital-twin
    - Cesium